// OMXS30 constituents (Yahoo Finance symbols, Stockholm = .ST)
export const OMXS30 = [
  { symbol: "ABB.ST", name: "ABB" },
  { symbol: "ALFA.ST", name: "Alfa Laval" },
  { symbol: "ASSA-B.ST", name: "Assa Abloy B" },
  { symbol: "AZN.ST", name: "AstraZeneca" },
  { symbol: "ATCO-A.ST", name: "Atlas Copco A" },
  { symbol: "ATCO-B.ST", name: "Atlas Copco B" },
  { symbol: "BOL.ST", name: "Boliden" },
  { symbol: "ELUX-B.ST", name: "Electrolux B" },
  { symbol: "ERIC-B.ST", name: "Ericsson B" },
  { symbol: "ESSITY-B.ST", name: "Essity B" },
  { symbol: "EVO.ST", name: "Evolution" },
  { symbol: "GETI-B.ST", name: "Getinge B" },
  { symbol: "HM-B.ST", name: "H&M B" },
  { symbol: "HEXA-B.ST", name: "Hexagon B" },
  { symbol: "INVE-B.ST", name: "Investor B" },
  { symbol: "KINV-B.ST", name: "Kinnevik B" },
  { symbol: "NDA-SE.ST", name: "Nordea" },
  { symbol: "NIBE-B.ST", name: "NIBE B" },
  { symbol: "SAAB-B.ST", name: "Saab B" },
  { symbol: "SAND.ST", name: "Sandvik" },
  { symbol: "SCA-B.ST", name: "SCA B" },
  { symbol: "SEB-A.ST", name: "SEB A" },
  { symbol: "SHB-A.ST", name: "Handelsbanken A" },
  { symbol: "SINCH.ST", name: "Sinch" },
  { symbol: "SKF-B.ST", name: "SKF B" },
  { symbol: "SWED-A.ST", name: "Swedbank A" },
  { symbol: "TEL2-B.ST", name: "Tele2 B" },
  { symbol: "TELIA.ST", name: "Telia" },
  { symbol: "VOLV-B.ST", name: "Volvo B" },
  { symbol: "SBB-B.ST", name: "SBB B" },
];
